
import face_recognition
import cv2
import os
import sys

# Previous workaround to ensure modules are found
sys.path.append('/mnt/d/tendency/.venv_new/lib/python3.12/site-packages')

print("--- Starting face_recognition debug script ---")

# Use an image that was successfully processed earlier in the log
# The main script created a directory like '0989', let's find it.
dirs = [d for d in os.listdir('.') if os.path.isdir(d) and d.isdigit()]
if not dirs:
    print("ERROR: Could not find the output directory (e.g., '0989').")
    print("Please run the main script once to generate the image directories.")
    sys.exit(1)

# Use the most recently created directory
latest_dir = max(dirs, key=lambda d: os.path.getmtime(d))
image_path = os.path.join(latest_dir, "rotated", f"{latest_dir}_001_0.jpg") 

print(f"Attempting to load image: {image_path}")

if not os.path.exists(image_path):
    print(f"ERROR: Image not found at {image_path}")
    print(f"Please check if the file exists. It should have been generated by the main script.")
else:
    try:
        image = cv2.imread(image_path)
        if image is None:
            print(f"ERROR: cv2.imread failed to load the image. It might be corrupted or in an unsupported format.")
        else:
            print("Image loaded successfully. Converting to RGB...")
            rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            
            print("Calling face_recognition.face_locations with 'hog' model...")
            # The call that is suspected of crashing
            face_locations = face_recognition.face_locations(rgb_image, model="hog")
            
            print("--- SUCCESS! ---")
            print(f"face_recognition.face_locations ran without crashing.")
            print(f"Found {len(face_locations)} face(s) in the image.")

    except Exception as e:
        print(f"--- SCRIPT FAILED WITH AN EXCEPTION ---")
        import traceback
        traceback.print_exc()
